apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-2
spec:
  replicas: 2
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        type: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx