apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      proyecto: ejemplo3
      utilidad: web
      version: "0.1"
  template:
    metadata:
      name: nginx
      labels:
        proyecto: ejemplo3
        utilidad: web
        version: "0.1"
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
