apiVersion: v1
kind: Service
metadata:
  name: nuestro-servicio-para-nginx-cip
spec:
  selector:
    proyecto: ejemplo3
    utilidad: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
