kind: Service
apiVersion: v1
metadata:
  name: nginx-loadbalancer
spec:
  type: LoadBalancer
  selector:
    proyecto: ejemplo3
    utilidad: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
